# Generated by Django 4.2.30 on 2026-08-06 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_app', '0002_alter_itempedido_id_alter_pedido_id_alter_produto_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoBanho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tipos_banho',
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='banho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque_app.tipobanho'),
        ),
    ]
