# Generated by Django 4.2.30 on 2026-08-11 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_app', '0005_alter_itempedido_produto_alter_itempedido_quantidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aguardando_pagamento', 'Aguardando pagamento'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=25),
        ),
    ]
